[package]
name = "finalize"
type = "bin"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
elgamal = { tag = "main", git = "https://github.com/shramee/noir-v1-elgamal", directory = "noir/lib" }